# All Apple Music contributor roles. Edit directly to add/remove entries.

ROLE_MAP: dict[str, str] = {
    '10-string bass guitar': '10-String Bass Guitar',
    '10-string guitar': '10-String Guitar',
    '11-string guitar': '11-String Guitar',
    '12-string acoustic guitar': '12-String Acoustic Guitar',
    '12-string bass guitar': '12-String Bass Guitar',
    '12-string electric guitar': '12-String Electric Guitar',
    '12-string fiddle': '12-String Fiddle',
    '12-string guitar': '12-String Guitar',
    '4-string banjo': '4-String Banjo',
    '4-string guitar': '4-String Guitar',
    '5-string banjo': '5-String Banjo',
    '5-string bass guitar': '5-String Bass Guitar',
    '6-string banjo': '6-String Banjo',
    '6-string bass guitar': '6-String Bass Guitar',
    '7-string banjo': '7-String Banjo',
    '7-string bass guitar': '7-String Bass Guitar',
    '7-string guitar': '7-String Guitar',
    '8-string bass guitar': '8-String Bass Guitar',
    '8-string guitar': '8-String Guitar',
    '9-string guitar': '9-String Guitar',
    'a cappella ensemble': 'A Cappella Ensemble',
    'accompaniment': 'Accompaniment',
    'accordion': 'Accordion',
    'accordion duo': 'Accordion Duo',
    'acoustic baritone guitar': 'Acoustic Baritone Guitar',
    'acoustic bass guitar': 'Acoustic Bass Guitar',
    'acoustic fretless guitar': 'Acoustic Fretless Guitar',
    'acoustic guitar': 'Acoustic Guitar',
    'acoustic rhythm guitar': 'Acoustic Rhythm Guitar',
    'acoustic slide guitar': 'Acoustic Slide Guitar',
    'actor': 'Actor',
    'adapter': 'Adapter',
    'adapter (religious text)': 'Adapter (Religious Text)',
    'adapter (traditional text)': 'Adapter (Traditional Text)',
    'additional engineer': 'Additional Engineer',
    'additional producer': 'Additional Producer',
    'additional vocals': 'Additional Vocals',
    'african percussion': 'African Percussion',
    'all instruments': 'All Instruments',
    'alphorn': 'Alphorn',
    'alto (vocal)': 'Alto (Vocal)',
    'alto clarinet': 'Alto Clarinet',
    'alto flute': 'Alto Flute',
    'alto guitar': 'Alto Guitar',
    'alto horn': 'Alto Horn',
    'alto lute': 'Alto Lute',
    'alto recorder': 'Alto Recorder',
    'alto saxophone': 'Alto Saxophone',
    'alto tenor (vocal)': 'Alto Tenor (Vocal)',
    'alto trombone': 'Alto Trombone',
    'alto viola': 'Alto Viola',
    'alto viola da gamba': 'Alto Viola da Gamba',
    'alto violin': 'Alto Violin',
    'alto zither': 'Alto Zither',
    'announcer': 'Announcer',
    'appalachian dulcimer': 'Appalachian Dulcimer',
    'archlute': 'Archlute',
    'army band': 'Army Band',
    'arp synthesizer': 'ARP Synthesizer',
    'arranged by': 'Arranger',
    'arranger': 'Arranger',
    'arranger (traditional)': 'Arranger (Traditional)',
    'art production': 'Art Production',
    'assistant arranger': 'Assistant Arranger',
    'assistant conductor': 'Assistant Conductor',
    'assistant director': 'Assistant Director',
    'assistant editing engineer': 'Assistant Editing Engineer',
    'assistant engineer': 'Assistant Engineer',
    'assistant mastering engineer': 'Assistant Mastering Engineer',
    'assistant mixing engineer': 'Assistant Mixing Engineer',
    'assistant producer': 'Assistant Producer',
    'assistant programming': 'Assistant Programming',
    'assistant recording engineer': 'Assistant Recording Engineer',
    'assistant strings engineer': 'Assistant Strings Engineer',
    'associate conductor': 'Associate Conductor',
    'associate producer': 'Associate Producer',
    'audio processing': 'Audio Processing',
    'audio restoration': 'Audio Restoration',
    'audio technician': 'Audio Technician',
    'autoharp': 'Autoharp',
    'b-flat clarinet': 'B-Flat Clarinet',
    'baby bass': 'Baby Bass',
    'background vocals': 'Background Vocals',
    'baglama': 'Baglama',
    'bagpipes': 'Bagpipes',
    'bajo quinto': 'Bajo Quinto',
    'bajo sexto': 'Bajo Sexto',
    'balafon': 'Balafon',
    'balalaika': 'Balalaika',
    'balance engineer': 'Balance Engineer',
    'ballet orchestra': 'Ballet Orchestra',
    'bamboo flute': 'Bamboo Flute',
    'bamboo saxophone': 'Bamboo Saxophone',
    'band': 'Band',
    'band conductor': 'Band Conductor',
    'band leader': 'Band Leader',
    'bandola': 'Bandola',
    'bandoneon': 'Bandoneon',
    'bandura': 'Bandura',
    'bandurria': 'Bandurria',
    'banjo': 'Banjo',
    'banjolin': 'Banjolin',
    'bansuri': 'Bansuri',
    'barbat': 'Barbat',
    'baritone (vocal)': 'Baritone (Vocal)',
    'baritone guitar': 'Baritone Guitar',
    'baritone horn': 'Baritone Horn',
    'baritone saxophone': 'Baritone Saxophone',
    'baritone trombone': 'Baritone Trombone',
    'baritone violin': 'Baritone Violin',
    'baroque alto trombone': 'Baroque Alto Trombone',
    'baroque bass trombone': 'Baroque Bass Trombone',
    'baroque bassoon': 'Baroque Bassoon',
    'baroque bassoon ensemble': 'Baroque Bassoon Ensemble',
    'baroque brass ensemble': 'Baroque Brass Ensemble',
    'baroque cello': 'Baroque Cello',
    'baroque chamber orchestra': 'Baroque Chamber Orchestra',
    'baroque choir': 'Baroque Choir',
    'baroque guitar': 'Baroque Guitar',
    'baroque harp': 'Baroque Harp',
    'baroque lute': 'Baroque Lute',
    'baroque music ensemble': 'Baroque Music Ensemble',
    'baroque music string ensemble': 'Baroque Music String Ensemble',
    'baroque music vocal ensemble': 'Baroque Music Vocal Ensemble',
    'baroque music wind ensemble': 'Baroque Music Wind Ensemble',
    'baroque oboe': 'Baroque Oboe',
    'baroque opera orchestra': 'Baroque Opera Orchestra',
    'baroque orchestra': 'Baroque Orchestra',
    'baroque quartet': 'Baroque Quartet',
    'baroque recorder': 'Baroque Recorder',
    'baroque trio': 'Baroque Trio',
    'baroque trumpet': 'Baroque Trumpet',
    'baroque viola': 'Baroque Viola',
    'baroque violin': 'Baroque Violin',
    'baroque wind ensemble': 'Baroque Wind Ensemble',
    'barrel organ': 'Barrel Organ',
    'baryton': 'Baryton',
    'based on the work of': 'Based on the Work of',
    'bass': 'Bass',
    'bass (vocal)': 'Bass (Vocal)',
    'bass banjo': 'Bass Banjo',
    'bass clarinet': 'Bass Clarinet',
    'bass drum': 'Bass Drum',
    'bass flute': 'Bass Flute',
    'bass flute-a-bec': 'Bass Flute-A-Bec',
    'bass guitar': 'Bass Guitar',
    'bass harmonica': 'Bass Harmonica',
    'bass harp': 'Bass Harp',
    'bass horn': 'Bass Horn',
    'bass lute': 'Bass Lute',
    'bass marimba': 'Bass Marimba',
    'bass oboe': 'Bass Oboe',
    'bass recorder': 'Bass Recorder',
    'bass saxophone': 'Bass Saxophone',
    'bass synthesizer': 'Bass Synthesizer',
    'bass technician': 'Bass Technician',
    'bass trombone': 'Bass Trombone',
    'bass trumpet': 'Bass Trumpet',
    'bass viola da gamba': 'Bass Viola Da Gamba',
    'bass violin': 'Bass Violin',
    'bass-baritone (vocal)': 'Bass-Baritone (Vocal)',
    'basset clarinet': 'Basset Clarinet',
    'basset horn': 'Basset Horn',
    'basset recorder': 'Basset Recorder',
    'basso continuo': 'Basso Continuo',
    'bassoon': 'Bassoon',
    'bassoon quartet': 'Bassoon Quartet',
    'batá drums': 'Batá Drums',
    'bayan': 'Bayan',
    'beatbox': 'Beatbox',
    'beats': 'Beats',
    'beigehu': 'Beigehu',
    'bells': 'Bells',
    'bendir': 'Bendir',
    'berimbau': 'Berimbau',
    'birbyne': 'Birbyne',
    'biwa': 'Biwa',
    'bodhrán drum': 'Bodhrán Drum',
    'bongos': 'Bongos',
    'book': 'Book',
    'bouzouki': 'Bouzouki',
    'boy soprano (vocal)': 'Boy Soprano (Vocal)',
    "boys' choir": "Boys' Choir",
    'brass': 'Brass',
    'brass and organ ensemble': 'Brass and Organ Ensemble',
    'brass arranger': 'Brass Arranger',
    'brass band': 'Brass Band',
    'brass conductor': 'Brass Conductor',
    'brass ensemble': 'Brass Ensemble',
    'brass instrument': 'Brass Instrument',
    'brass octet': 'Brass Octet',
    'brass orchestra': 'Brass Orchestra',
    'brass quartet': 'Brass Quartet',
    'brass quintet': 'Brass Quintet',
    'brass septet': 'Brass Septet',
    'bugle': 'Bugle',
    'bukkehorn': 'Bukkehorn',
    'button accordion': 'Button Accordion',
    'byzantine lyra': 'Byzantine Lyra',
    'c-melody saxophone': 'C-Melody Saxophone',
    'cabasa': 'Cabasa',
    'cadenza': 'Cadenza',
    'cajon': 'Cajon',
    'cajun fiddle': 'Cajun Fiddle',
    'camera operator': 'Camera Operator',
    'cantor': 'Cantor',
    'carillon': 'Carillon',
    'cast': 'Cast',
    'castanets': 'Castanets',
    'cathedral choir': 'Cathedral Choir',
    'cavaquinho': 'Cavaquinho',
    'caxixi': 'Caxixi',
    'celesta': 'Celesta',
    'cello': 'Cello',
    'cello duo': 'Cello Duo',
    'cello octet': 'Cello Octet',
    'cello quartet': 'Cello Quartet',
    'celtic flute': 'Celtic Flute',
    'celtic harp': 'Celtic Harp',
    'chalumeau': 'Chalumeau',
    'chamber choir': 'Chamber Choir',
    'chamber music ensemble': 'Chamber Music Ensemble',
    'chamber orchestra': 'Chamber Orchestra',
    'chamber organ': 'Chamber Organ',
    'chamberlain strings': 'Chamberlain Strings',
    'chant conductor': 'Chant Conductor',
    'chant vocals': 'Chant Vocals',
    'chapman stick': 'Chapman Stick',
    'charango': 'Charango',
    "children's choir": "Children's Choir",
    "children's vocals": "Children's Vocals",
    'chinese flute': 'Chinese Flute',
    'chinese traditional music ensemble': 'Chinese Traditional Music Ensemble',
    'chitarrone': 'Chitarrone',
    'choir': 'Choir',
    'choir arranger': 'Choir Arranger',
    'choir boy': 'Choir Boy',
    'choir conductor': 'Choir Conductor',
    'choir director': 'Choir Director',
    'choral conductor': 'Choral Conductor',
    'choreography': 'Choreography',
    'chorus': 'Chorus',
    'chorus arranger': 'Chorus Arranger',
    'chorus conductor': 'Chorus Conductor',
    'chorus director': 'Chorus Director',
    'christmas carols ensemble': 'Christmas Carols Ensemble',
    'chromatic harmonica': 'Chromatic Harmonica',
    'cimbalom': 'Cimbalom',
    'cinematography': 'Cinematography',
    'cittern': 'Cittern',
    'clap stick': 'Clap Stick',
    'claps': 'Claps',
    'clarinet': 'Clarinet',
    'clarinet orchestra': 'Clarinet Orchestra',
    'clarinet quartet': 'Clarinet Quartet',
    'clarinet trio': 'Clarinet Trio',
    'classical ensemble': 'Classical Ensemble',
    'classical guitar': 'Classical Guitar',
    'classical vocals': 'Classical Vocals',
    'claves': 'Claves',
    'clavichord': 'Clavichord',
    'clavier': 'Clavier',
    'clavinet': 'Clavinet',
    'co-arranger': 'Co-Arranger',
    'co-composer': 'Co-Composer',
    'co-executive producer': 'Co-Executive Producer',
    'co-producer': 'Co-Producer',
    'comedian': 'Comedian',
    'commentary': 'Commentary',
    'compilation producer': 'Compilation Producer',
    'composer': 'Composer',
    'composers': 'Composer',
    'composition ascribed to': 'Composition Ascribed to',
    'computer graphics': 'Computer Graphics',
    'concert producer': 'Concert Producer',
    'concertina': 'Concertina',
    'conductor': 'Conductor',
    'congas': 'Congas',
    'contains a sample of': 'Samples',
    'contemporary music chamber orchestra': 'Contemporary Music Chamber Orchestra',
    'contemporary music ensemble': 'Contemporary Music Ensemble',
    'contemporary music orchestra': 'Contemporary Music Orchestra',
    'contemporary music quartet': 'Contemporary Music Quartet',
    'contemporary music trio': 'Contemporary Music Trio',
    'continuo': 'Continuo',
    'contrabass': 'Contrabass',
    'contrabass clarinet': 'Contrabass Clarinet',
    'contrabass flute': 'Contrabass Flute',
    'contrabass recorder': 'Contrabass Recorder',
    'contrabass saxophone': 'Contrabass Saxophone',
    'contrabass trombone': 'Contrabass Trombone',
    'contrabassoon': 'Contrabassoon',
    'contralto (vocal)': 'Contralto (Vocal)',
    'contralto clarinet': 'Contralto Clarinet',
    'copyist': 'Copyist',
    'cornet': 'Cornet',
    'cornetto': 'Cornetto',
    'corno da caccia': 'Corno da Caccia',
    'coro': 'Coro',
    'costume design': 'Costume Design',
    'counter-tenor (vocal)': 'Counter-Tenor (Vocal)',
    'cover art': 'Cover Art',
    'cover photography': 'Cover Photography',
    'cowbell': 'Cowbell',
    'creative director': 'Creative Director',
    'crossover duo': 'Crossover Duo',
    'crossover ensemble': 'Crossover Ensemble',
    'crossover trio': 'Crossover Trio',
    'crotales': 'Crotales',
    'crumhorn': 'Crumhorn',
    'cuatro venezolano': 'Cuatro Venezolano',
    'cuica': 'Cuica',
    'cymbals': 'Cymbals',
    'dadi': 'Dadi',
    'daf': 'Daf',
    'dancer': 'Dancer',
    'darbuka': 'Darbuka',
    'daruan': 'Daruan',
    'daxophone': 'Daxophone',
    'dhol': 'Dhol',
    'dialogue': 'Dialogue',
    'didgeridoo': 'Didgeridoo',
    'dilruba': 'Dilruba',
    'dizi': 'Dizi',
    'dj': 'DJ',
    'djembe': 'Djembe',
    'dobro': 'Dobro',
    'dojo': 'Dojo',
    'domra': 'Domra',
    'double bass': 'Double Bass',
    'double bass ensemble': 'Double Bass Ensemble',
    'double bass quartet': 'Double Bass Quartet',
    'double flute': 'Double Flute',
    'double recorder': 'Double Recorder',
    'doumbek': 'Doumbek',
    'drawing': 'Drawing',
    'drum machine': 'Drum Machine',
    'drum programming': 'Drum Programming',
    'drum technician': 'Drum Technician',
    'drums': 'Drums',
    'duduk': 'Duduk',
    'duet vocals': 'Duet Vocals',
    'dulcian': 'Dulcian',
    'dulcimer': 'Dulcimer',
    'dutar': 'Dutar',
    'e-bow': 'E-Bow',
    'early music chamber choir': 'Early Music Chamber Choir',
    'early music chamber orchestra': 'Early Music Chamber Orchestra',
    'early music choir': 'Early Music Choir',
    'early music duo': 'Early Music Duo',
    'early music ensemble': 'Early Music Ensemble',
    'early music instrument': 'Early Music Instrument',
    'early music orchestra': 'Early Music Orchestra',
    'early music trio': 'Early Music Trio',
    'early music vocal ensemble': 'Early Music Vocal Ensemble',
    'editing engineer': 'Editing Engineer',
    'electric banjo': 'Electric Banjo',
    'electric bass guitar': 'Electric Bass Guitar',
    'electric cello': 'Electric Cello',
    'electric fretless guitar': 'Electric Fretless Guitar',
    'electric guitar': 'Electric Guitar',
    'electric mandolin': 'Electric Mandolin',
    'electric piano': 'Electric Piano',
    'electric sitar': 'Electric Sitar',
    'electric upright bass': 'Electric Upright Bass',
    'electric violin': 'Electric Violin',
    'electronic instrument': 'Electronic Instrument',
    'electronic music ensemble': 'Electronic Music Ensemble',
    'electronic percussion': 'Electronic Percussion',
    'electronics': 'Electronics',
    'engineer': 'Engineer',
    'engineers': 'Engineer',
    'english horn': 'English Horn',
    'engraving': 'Engraving',
    'ensemble': 'Ensemble',
    'ensemble director': 'Ensemble Director',
    'equipment technician': 'Equipment Technician',
    'erhu': 'Erhu',
    'euphonium': 'Euphonium',
    'ewi': 'EWI',
    'executive produced by': 'Executive Producer',
    'executive producer': 'Executive Producer',
    'executive producers': 'Executive Producer',
    'fairlight cmi': 'Fairlight CMI',
    'farfisa': 'Farfisa',
    'fiddle': 'Fiddle',
    'fife': 'Fife',
    'film director': 'Film Director',
    'film editor': 'Film Editor',
    'film producer': 'Film Producer',
    'finger cymbals': 'Finger Cymbals',
    'finger snaps': 'Finger Snaps',
    'first cello': 'First Cello',
    'first violin': 'First Violin',
    'flageolet': 'Flageolet',
    'flamenco cajón': 'Flamenco Cajón',
    'flamenco guitar': 'Flamenco Guitar',
    'flugelhorn': 'Flugelhorn',
    'flute': 'Flute',
    'flute ensemble': 'Flute Ensemble',
    'flute quartet': 'Flute Quartet',
    'flute quintet': 'Flute Quintet',
    'folk music ensemble': 'Folk Music Ensemble',
    'folk music orchestra': 'Folk Music Orchestra',
    'foot stomping': 'Foot Stomping',
    'fortepiano': 'Fortepiano',
    'frame drum': 'Frame Drum',
    'french horn': 'French Horn',
    'fretless bass guitar': 'Fretless Bass Guitar',
    'fretless guitar': 'Fretless Guitar',
    'fujara': 'Fujara',
    'funde': 'Funde',
    'fuzz guitar': 'Fuzz Guitar',
    'gadulka': 'Gadulka',
    'gamelan': 'Gamelan',
    'gang vocals': 'Gang Vocals',
    'gaodi': 'Gaodi',
    'gaohu': 'Gaohu',
    'gehu': 'Gehu',
    'ghatam': 'Ghatam',
    "girls' choir": "Girls' Choir",
    'gittern': 'Gittern',
    'glass harmonica': 'Glass Harmonica',
    'glockenspiel': 'Glockenspiel',
    'gong': 'Gong',
    'gospel choir': 'Gospel Choir',
    'gothic harp': 'Gothic Harp',
    'graphic design': 'Graphic Design',
    'great bass recorder': 'Great Bass Recorder',
    'gregorian chant choir': 'Gregorian Chant Choir',
    'gregorian chant ensemble': 'Gregorian Chant Ensemble',
    'group': 'Group',
    'guitar': 'Guitar',
    'guitar duo': 'Guitar Duo',
    'guitar quartet': 'Guitar Quartet',
    'guitar synthesizer': 'Guitar Synthesizer',
    'guitar technician': 'Guitar Technician',
    'guitar trio': 'Guitar Trio',
    'guitarron': 'Guitarron',
    'guqin': 'Guqin',
    'gut string guitar': 'Gut String Guitar',
    'guzheng': 'Guzheng',
    'güira': 'Güira',
    'güiro': 'Güiro',
    'güícharo': 'Güícharo',
    'haegeum': 'Haegeum',
    'hammered dulcimer': 'Hammered Dulcimer',
    'hammond organ': 'Hammond Organ',
    'hand claps': 'Hand Claps',
    'handbell choir': 'Handbell Choir',
    'hang': 'Hang',
    'hardanger fiddle': 'Hardanger Fiddle',
    'harmonica': 'Harmonica',
    'harmonium': 'Harmonium',
    'harmony vocals': 'Harmony Vocals',
    'harp': 'Harp',
    'harp ensemble': 'Harp Ensemble',
    'harpsichord': 'Harpsichord',
    'harpsichord technician': 'Harpsichord Technician',
    'harpsichord tuner': 'Harpsichord Tuner',
    'haute contre vocals': 'Haute Contre Vocals',
    'heckelphone': 'Heckelphone',
    'herald trumpet': 'Herald Trumpet',
    'hi-hat': 'Hi-Hat',
    'hi-string guitar': 'Hi-String Guitar',
    'hichiriki': 'Hichiriki',
    'high tenor (vocal)': 'High Tenor (Vocal)',
    'historical bassoon': 'Historical Bassoon',
    'historical flutes': 'Historical Flutes',
    'historical guitar': 'Historical Guitar',
    'historical harp': 'Historical Harp',
    'historical percussion': 'Historical Percussion',
    'horn': 'Horn',
    'horn arranger': 'Horn Arranger',
    'horn conductor': 'Horn Conductor',
    'horn ensemble': 'Horn Ensemble',
    'horn quartet': 'Horn Quartet',
    'horn section': 'Horn Section',
    'host': 'Host',
    'huqin': 'Huqin',
    'hurdy gurdy': 'Hurdy Gurdy',
    'illustrator': 'Illustrator',
    'immersive audio engineer': 'Immersive Audio Engineer',
    'immersive mastering engineer': 'Immersive Mastering Engineer',
    'immersive mixing engineer': 'Immersive Mixing Engineer',
    'indian flute': 'Indian Flute',
    'instrumental ensemble': 'Instrumental Ensemble',
    'interviewee': 'Interviewee',
    'interviewer': 'Interviewer',
    'intro vocals': 'Intro Vocals',
    'introduction by': 'Introduction by',
    'irish flute': 'Irish Flute',
    'irish whistle': 'Irish Whistle',
    'japanese flute': 'Japanese Flute',
    'jazz ensemble': 'Jazz Ensemble',
    'jazz trio': 'Jazz Trio',
    'kalimba': 'Kalimba',
    'kamancheh': 'Kamancheh',
    'kantele': 'Kantele',
    'kanun': 'Kanun',
    'kaval': 'Kaval',
    'kazoo': 'Kazoo',
    'keyboard arranger': 'Keyboard Arranger',
    'keyboard bass': 'Keyboard Bass',
    'keyboard instrument': 'Keyboard Instrument',
    'keyboard synth': 'Keyboard Synth',
    'keyboard technician': 'Keyboard Technician',
    'keyboards': 'Keyboards',
    'keytar': 'Keytar',
    'khene': 'Khene',
    'kora': 'Kora',
    'koto': 'Koto',
    'kugo': 'Kugo',
    'lap cello': 'Lap Cello',
    'lap slide guitar': 'Lap Slide Guitar',
    'lap steel guitar': 'Lap Steel Guitar',
    'lautenwerck': 'Lautenwerck',
    'lead acoustic guitar': 'Lead Acoustic Guitar',
    'lead electric guitar': 'Lead Electric Guitar',
    'lead guitar': 'Lead Guitar',
    'lead violin': 'Lead Violin',
    'lead vocals': 'Lead Vocals',
    'leaf': 'Leaf',
    'librettist': 'Librettist',
    'libretto editing': 'Libretto Editing',
    'lighting design': 'Lighting Design',
    'lirone': 'Lirone',
    'lithography': 'Lithography',
    'liuqin': 'Liuqin',
    'live mixing engineer': 'Live Mixing Engineer',
    'live production': 'Live Production',
    'live recording engineer': 'Live Recording Engineer',
    'loops': 'Loops',
    'low whistle': 'Low Whistle',
    'lowrey organ': 'Lowrey Organ',
    'lute': 'Lute',
    'lute duo': 'Lute Duo',
    'lyra viol': 'Lyra Viol',
    'lyre': 'Lyre',
    'lyricists': 'Lyricist',
    'lyricon': 'Lyricon',
    'lyrics': 'Lyrics',
    'mandocello': 'Mandocello',
    'mandola': 'Mandola',
    'mandolin': 'Mandolin',
    'maracas': 'Maracas',
    'marching band': 'Marching Band',
    'marimba': 'Marimba',
    'mastered by': 'Mastering Engineer',
    'mastering engineer': 'Mastering Engineer',
    'mbira': 'Mbira',
    'mc': 'MC',
    'medieval flute': 'Medieval Flute',
    'medieval harp': 'Medieval Harp',
    'medieval music ensemble': 'Medieval Music Ensemble',
    'medieval music quartet': 'Medieval Music Quartet',
    'medieval music vocal ensemble': 'Medieval Music Vocal Ensemble',
    'mellophone': 'Mellophone',
    'mellotron': 'Mellotron',
    'melodeon': 'Melodeon',
    'melodica': 'Melodica',
    "men's choir": "Men's Choir",
    'metallophone': 'Metallophone',
    'mezzo violin': 'Mezzo Violin',
    'mezzo-soprano (vocal)': 'Mezzo-Soprano (Vocal)',
    'military band': 'Military Band',
    'military choir': 'Military Choir',
    'mixed artist': 'Mixed Artist',
    'mixed by': 'Mixing Engineer',
    'mixing engineer': 'Mixing Engineer',
    'modular synth': 'Modular Synth',
    'mong': 'Mong',
    'moog': 'Moog',
    'mouth harp': 'Mouth Harp',
    'mouth organ': 'Mouth Organ',
    'mridangam': 'Mridangam',
    'multi-instrumentalist': 'Multi-Instrumentalist',
    'musette': 'Musette',
    'music director': 'Music Director',
    'music supervisor': 'Music Supervisor',
    'musical saw': 'Musical Saw',
    'muted trombone': 'Muted Trombone',
    'muted trumpet': 'Muted Trumpet',
    'narrator': 'Narrator',
    'native american flute': 'Native American Flute',
    'natural horn': 'Natural Horn',
    'ney': 'Ney',
    'nyckelharpa': 'Nyckelharpa',
    'nylon-string guitar': 'Nylon-String Guitar',
    'oboe': 'Oboe',
    "oboe d'amore": "Oboe d'Amore",
    'oboe da caccia': 'Oboe Da Caccia',
    'ocarina': 'Ocarina',
    'omnichord': 'Omnichord',
    'ondes martenot': 'Ondes Martenot',
    'opera and ballet orchestra': 'Opera and Ballet Orchestra',
    'opera choir': 'Opera Choir',
    'opera company': 'Opera Company',
    'opera orchestra': 'Opera Orchestra',
    'ophicleide': 'Ophicleide',
    'orchestra': 'Orchestra',
    'orchestra conductor': 'Orchestra Conductor',
    'orchestra director': 'Orchestra Director',
    'orchestra leader': 'Orchestra Leader',
    'orchestra manager': 'Orchestra Manager',
    'orchestrator': 'Orchestrator',
    'organ': 'Organ',
    'organ pedals': 'Organ Pedals',
    'organ technician': 'Organ Technician',
    'organetto': 'Organetto',
    'original arranger': 'Original Arranger',
    'original engineering': 'Original Engineering',
    'original mastering engineer': 'Original Mastering Engineer',
    'original mixing engineer': 'Original Mixing Engineer',
    'original producer': 'Original Producer',
    'oud': 'Oud',
    'outro vocals': 'Outro Vocals',
    'overdub engineer': 'Overdub Engineer',
    'package design': 'Package Design',
    'paintings': 'Paintings',
    'pakhavaj': 'Pakhavaj',
    'palmas': 'Palmas',
    'pan flute': 'Pan Flute',
    'pandeiro': 'Pandeiro',
    'panderos': 'Panderos',
    'pardessus de viole': 'Pardessus de Viole',
    'parlor guitar': 'Parlor Guitar',
    'pedal steel guitar': 'Pedal Steel Guitar',
    'percussion': 'Percussion',
    'percussion arranger': 'Percussion Arranger',
    'percussion duo': 'Percussion Duo',
    'percussion ensemble': 'Percussion Ensemble',
    'percussion instrument': 'Percussion Instrument',
    'percussion quartet': 'Percussion Quartet',
    'performers': 'Performer',
    'period instrument orchestra': 'Period Instrument Orchestra',
    'philharmonic choir': 'Philharmonic Choir',
    'philharmonic orchestra': 'Philharmonic Orchestra',
    'photo editor': 'Photo Editor',
    'photography': 'Photography',
    'piano': 'Piano',
    'piano duo': 'Piano Duo',
    'piano ensemble': 'Piano Ensemble',
    'piano quartet': 'Piano Quartet',
    'piano quintet': 'Piano Quintet',
    'piano technician': 'Piano Technician',
    'piano trio': 'Piano Trio',
    'piano tuner': 'Piano Tuner',
    'piccolo bass': 'Piccolo Bass',
    'piccolo flute': 'Piccolo Flute',
    'piccolo trumpet': 'Piccolo Trumpet',
    'pierrot ensemble': 'Pierrot Ensemble',
    'pipa': 'Pipa',
    'pipe': 'Pipe',
    'pipe ensemble': 'Pipe Ensemble',
    'pipe organ': 'Pipe Organ',
    'pipes': 'Pipes',
    'playback singer': 'Playback Singer',
    'pocket trumpet': 'Pocket Trumpet',
    'poetry': 'Poetry',
    'pops orchestra': 'Pops Orchestra',
    'portraits': 'Portraits',
    'portuguese guitar': 'Portuguese Guitar',
    'positive organ': 'Positive Organ',
    'post horn': 'Post Horn',
    'post production assistant': 'Post Production Assistant',
    'post production director': 'Post Production Director',
    'post production editor': 'Post Production Editor',
    'post production engineer': 'Post Production Engineer',
    'post production mixing engineer': 'Post Production Mixing Engineer',
    'post production supervisor': 'Post Production Supervisor',
    'prepared piano': 'Prepared Piano',
    'primera voz': 'Primera Voz',
    'produced by': 'Producer',
    'producer': 'Producer',
    'producers': 'Producer',
    'programming': 'Programming',
    'psaltery': 'Psaltery',
    'pump organ': 'Pump Organ',
    'rabab': 'Rabab',
    'radio choir': 'Radio Choir',
    'radio orchestra': 'Radio Orchestra',
    'ragga mc': 'Ragga MC',
    'rap': 'Rap',
    'realization (figured bass)': 'Realization (figured bass)',
    'rebec': 'Rebec',
    'reconstruction': 'Reconstruction',
    'recorded by': 'Recording Engineer',
    'recorder': 'Recorder',
    'recorder ensemble': 'Recorder Ensemble',
    'recorder quartet': 'Recorder Quartet',
    'recorder quintet': 'Recorder Quintet',
    'recording engineer': 'Recording Engineer',
    'recording supervisor': 'Recording Supervisor',
    'recording technician': 'Recording Technician',
    'reed organ': 'Reed Organ',
    'reeds': 'Reeds',
    'reissue producer': 'Reissue Producer',
    'remix producer': 'Remix Producer',
    'remixer': 'Remixer',
    'renaissance flute': 'Renaissance Flute',
    'renaissance guitar': 'Renaissance Guitar',
    'renaissance music chamber choir': 'Renaissance Music Chamber Choir',
    'renaissance music ensemble': 'Renaissance Music Ensemble',
    'renaissance music quartet': 'Renaissance Music Quartet',
    'renaissance music wind ensemble': 'Renaissance Music Wind Ensemble',
    'repeater drum': 'Repeater Drum',
    'requinto guitar': 'Requinto Guitar',
    'requinto jarocho': 'Requinto Jarocho',
    'research': 'Research',
    'resonator guitar': 'Resonator Guitar',
    'revision': 'Revision',
    'rhodes piano': 'Rhodes Piano',
    'rhythm guitar': 'Rhythm Guitar',
    'rhythm programming': 'Rhythm Programming',
    'romantic guitar': 'Romantic Guitar',
    'romantic music ensemble': 'Romantic Music Ensemble',
    'ruan': 'Ruan',
    'russian folk music ensemble': 'Russian Folk Music Ensemble',
    'russian guitar': 'Russian Guitar',
    'sabar ensemble': 'Sabar Ensemble',
    'sackbut': 'Sackbut',
    'sacred music choir': 'Sacred Music Choir',
    'sacred music ensemble': 'Sacred Music Ensemble',
    'sampled artist': 'Sampled Artist',
    'sampler': 'Sampler',
    'santur': 'Santur',
    'sarangi': 'Sarangi',
    'sarod': 'Sarod',
    'saxello': 'Saxello',
    'saxophone': 'Saxophone',
    'saxophone arranger': 'Saxophone Arranger',
    'saxophone quartet': 'Saxophone Quartet',
    'saxophone quintet': 'Saxophone Quintet',
    'score editor': 'Score Editor',
    'score preparation': 'Score Preparation',
    'score producer': 'Score Producer',
    'scratches': 'Scratches',
    'screams': 'Screams',
    'screenwriter': 'Screenwriter',
    'second cello': 'Second Cello',
    'second violin': 'Second Violin',
    'second vocals': 'Second Vocals',
    'segunda voz': 'Segunda Voz',
    'serpent': 'Serpent',
    'set designer': 'Set Designer',
    'shaker': 'Shaker',
    'shakuhachi': 'Shakuhachi',
    'shamisen': 'Shamisen',
    'shawm': 'Shawm',
    'shehnai': 'Shehnai',
    'shekere': 'Shekere',
    'sheng': 'Sheng',
    'shouts': 'Shouts',
    'shō': 'Shō',
    'sistrum': 'Sistrum',
    'sitar': 'Sitar',
    'sleigh bells': 'Sleigh Bells',
    'slide guitar': 'Slide Guitar',
    'slide trumpet': 'Slide Trumpet',
    'slide whistle': 'Slide Whistle',
    'snare drum': 'Snare Drum',
    'solo': 'Solo',
    'songwriter': 'Songwriter',
    'sopilka': 'Sopilka',
    'sopranino recorder': 'Sopranino Recorder',
    'sopranino saxophone': 'Sopranino Saxophone',
    'soprano (vocal)': 'Soprano (Vocal)',
    'soprano clarinet': 'Soprano Clarinet',
    'soprano cornet': 'Soprano Cornet',
    'soprano flute': 'Soprano Flute',
    'soprano recorder': 'Soprano Recorder',
    'soprano saxophone': 'Soprano Saxophone',
    'soprano trombone': 'Soprano Trombone',
    'soprano viola da gamba': 'Soprano Viola da Gamba',
    'soprano violin': 'Soprano Violin',
    'sound design': 'Sound Design',
    'sound effects': 'Sound Effects',
    'soundtrack producer': 'Soundtrack Producer',
    'sousaphone': 'Sousaphone',
    'speaker': 'Speaker',
    'special effects': 'Special Effects',
    'spinet': 'Spinet',
    'spoken word': 'Spoken Word',
    'spoons': 'Spoons',
    'stage director': 'Stage Director',
    'stage manager': 'Stage Manager',
    'stage technician': 'Stage Technician',
    'steel drum': 'Steel Drum',
    'steel guitar': 'Steel Guitar',
    'streichmelodion': 'Streichmelodion',
    'string arranger': 'String Arranger',
    'string conductor': 'String Conductor',
    'string ensemble': 'String Ensemble',
    'string instrument': 'String Instrument',
    'string octet': 'String Octet',
    'string orchestra': 'String Orchestra',
    'string quartet': 'String Quartet',
    'string quintet': 'String Quintet',
    'string section': 'String Section',
    'string sextet': 'String Sextet',
    'string trio': 'String Trio',
    'strings': 'Strings',
    'strings engineer': 'Strings Engineer',
    'stritch': 'Stritch',
    'stroh violin': 'Stroh Violin',
    'studio choir': 'Studio Choir',
    'studio orchestra': 'Studio Orchestra',
    'studio personnel': 'Studio Personnel',
    'studio technician': 'Studio Technician',
    'stylist': 'Stylist',
    'stylophone': 'Stylophone',
    'suona': 'Suona',
    'surbahar': 'Surbahar',
    'surdo': 'Surdo',
    'swing music band': 'Swing Music Band',
    'symphonic band': 'Symphonic Band',
    'symphony choir': 'Symphony Choir',
    'symphony chorus': 'Symphony Chorus',
    'symphony orchestra': 'Symphony Orchestra',
    'synclavier': 'Synclavier',
    'synth bass': 'Synth Bass',
    'synth guitar': 'Synth Guitar',
    'synth pads': 'Synth Pads',
    'synth percussion': 'Synth Percussion',
    'synth strings': 'Synth Strings',
    'synthesizer': 'Synthesizer',
    'synthesizer programming': 'Synthesizer Programming',
    'tabla': 'Tabla',
    'tabor': 'Tabor',
    'tafelklavier': 'Tafelklavier',
    'taiko drums': 'Taiko Drums',
    'talkbox': 'Talkbox',
    'talking drum': 'Talking Drum',
    'tamborim': 'Tamborim',
    'tamboura': 'Tamboura',
    'tambourine': 'Tambourine',
    'tanbur': 'Tanbur',
    'tango ensemble': 'Tango Ensemble',
    'tanpura': 'Tanpura',
    'taonga pūoro': 'Taonga Pūoro',
    'tap dancer': 'Tap Dancer',
    'tape': 'Tape',
    'tape editor': 'Tape Editor',
    'tape operator': 'Tape Operator',
    'tape preparation': 'Tape Preparation',
    'tar': 'Tar',
    'temple blocks': 'Temple Blocks',
    'tenor (vocal)': 'Tenor (Vocal)',
    'tenor banjo': 'Tenor Banjo',
    'tenor drums': 'Tenor Drums',
    'tenor guitar': 'Tenor Guitar',
    'tenor horn': 'Tenor Horn',
    'tenor recorder': 'Tenor Recorder',
    'tenor sackbut': 'Tenor Sackbut',
    'tenor saxophone': 'Tenor Saxophone',
    'tenor trombone': 'Tenor Trombone',
    'tenor viol': 'Tenor Viol',
    'tenor viola da gamba': 'Tenor Viola da Gamba',
    'tenor violin': 'Tenor Violin',
    'text': 'Text',
    'theorbo': 'Theorbo',
    'theremin': 'Theremin',
    'tibetan bowls': 'Tibetan Bowls',
    'timbales': 'Timbales',
    'timpani': 'Timpani',
    'tin whistle': 'Tin Whistle',
    'toasting': 'Toasting',
    'tom-toms': 'Tom-Toms',
    'tonmeister': 'Tonmeister',
    'toy piano': 'Toy Piano',
    'transcription': 'Transcription',
    'transfer engineer': 'Transfer Engineer',
    'translation': 'Translation',
    'transverse flute': 'Transverse Flute',
    'trautonium': 'Trautonium',
    'traverso': 'Traverso',
    'treble (vocal)': 'Treble (Vocal)',
    'treble recorder': 'Treble Recorder',
    'treble viola da gamba': 'Treble Viola da Gamba',
    'treble violin': 'Treble Violin',
    'tres': 'Tres',
    'triangle': 'Triangle',
    'trombone': 'Trombone',
    'trombone quartet': 'Trombone Quartet',
    'trumpet': 'Trumpet',
    'trumpet arranger': 'Trumpet Arranger',
    'trumpet duo': 'Trumpet Duo',
    'trumpet ensemble': 'Trumpet Ensemble',
    'tuba': 'Tuba',
    'tuba ensemble': 'Tuba Ensemble',
    'tubular bells': 'Tubular Bells',
    'turntables': 'Turntables',
    'txistu': 'Txistu',
    'typesetting': 'Typesetting',
    'typography': 'Typography',
    'udu': 'Udu',
    'uilleann pipes': 'Uilleann Pipes',
    'ukulele': 'Ukulele',
    'upright bass': 'Upright Bass',
    'upright piano': 'Upright Piano',
    'valve trombone': 'Valve Trombone',
    'veena': 'Veena',
    'vibes': 'Vibes',
    'vibraphone': 'Vibraphone',
    'vibraslap': 'Vibraslap',
    'video director': 'Video Director',
    'video editor': 'Video Editor',
    'video producer': 'Video Producer',
    'video production': 'Video Production',
    'videographer': 'Videographer',
    'vielle': 'Vielle',
    'vihuela': 'Vihuela',
    'viol': 'Viol',
    'viol consort': 'Viol Consort',
    'viola': 'Viola',
    "viola d'amore": "Viola d'Amore",
    'viola da gamba': 'Viola da Gamba',
    'viola da gamba ensemble': 'Viola da Gamba Ensemble',
    'viola quartet': 'Viola Quartet',
    'violetta': 'Violetta',
    'violin': 'Violin',
    'violin duo': 'Violin Duo',
    'violin ensemble': 'Violin Ensemble',
    'violoncello': 'Violoncello',
    'violone': 'Violone',
    'violone grosso': 'Violone Grosso',
    'virginal': 'Virginal',
    'vocal adapter': 'Vocal Adapter',
    'vocal arranger': 'Vocal Arranger',
    'vocal conductor': 'Vocal Conductor',
    'vocal director': 'Vocal Director',
    'vocal duo': 'Vocal Duo',
    'vocal effects': 'Vocal Effects',
    'vocal ensemble': 'Vocal Ensemble',
    'vocal mixing engineer': 'Vocal Mixing Engineer',
    'vocal producer': 'Vocal Producer',
    'vocal programming': 'Vocal Programming',
    'vocal quartet': 'Vocal Quartet',
    'vocal recording engineer': 'Vocal Recording Engineer',
    'vocal trio': 'Vocal Trio',
    'vocaloid': 'Vocaloid',
    'vocals': 'Vocals',
    'vocoder': 'Vocoder',
    'wardrobe': 'Wardrobe',
    'washboard': 'Washboard',
    'whistle': 'Whistle',
    'whistling': 'Whistling',
    'wind arranger': 'Wind Arranger',
    'wind chimes': 'Wind Chimes',
    'wind ensemble': 'Wind Ensemble',
    'wind instrument': 'Wind Instrument',
    'wind octet': 'Wind Octet',
    'wind orchestra': 'Wind Orchestra',
    'wind quartet': 'Wind Quartet',
    'wind quintet': 'Wind Quintet',
    'wind trio': 'Wind Trio',
    "women's choir": "Women's Choir",
    'wood block': 'Wood Block',
    'wood flute': 'Wood Flute',
    'wood recorder': 'Wood Recorder',
    'wood whistle': 'Wood Whistle',
    'woodwind arranger': 'Woodwind Arranger',
    'woodwind ensemble': 'Woodwind Ensemble',
    'woodwind instrument': 'Woodwind Instrument',
    'woodwind quintet': 'Woodwind Quintet',
    'woodwinds': 'Woodwinds',
    'worship leader': 'Worship Leader',
    'writer': 'Writer',
    'writers': 'Writer',
    'written by': 'Writer',
    'wurlitzer piano': 'Wurlitzer Piano',
    'xylophone': 'Xylophone',
    'xylorimba': 'Xylorimba',
    'yangqin': 'Yangqin',
    'yokobue': 'Yokobue',
    'youth choir': 'Youth Choir',
    'youth orchestra': 'Youth Orchestra',
    'zarb': 'Zarb',
    'zhongdi': 'Zhongdi',
    'zhonghu': 'Zhonghu',
    'zhongruan': 'Zhongruan',
    'zither': 'Zither',
    'đàn tranh': 'Đàn Tranh',
}

ALL_ROLE_KEYS: frozenset[str] = frozenset(ROLE_MAP)
